/**
用于在qic_db数据库里建立资讯的表, 这些都是用tungsten来生成的关于gta_data的资讯的小表.
表名的规则为:
c_原始表名_lst
*/
use qic_db;

DROP TABLE IF EXISTS `c_ann_announcementinfo_lst`;

CREATE TABLE `c_ann_announcementinfo_lst` (
  `ANNOUNCEMENTID` bigint(20) NOT NULL COMMENT '公告ID',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公告日期',
  `TITLE` varchar(510) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公告标题',
  `FILESIZE` int(11) DEFAULT NULL COMMENT '公告大小',
  `ANNOUNCEMENTTYPE` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公告格式',
  `ANNOUNCEMENTROUTE` varchar(800) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公告路径',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`ANNOUNCEMENTID`),
  KEY `dd_in_1` (`DECLAREDATE`),
  KEY `IUM51089333` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_ann_classify_lst`;

CREATE TABLE `c_ann_classify_lst` (
  `ANNOUNCEMENTID` bigint(20) NOT NULL COMMENT '公告ID',
  `CLASSIFYID` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '公告分类编码',
  `CLASSIFYNAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公告分类名称',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公告日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`ANNOUNCEMENTID`,`CLASSIFYID`),
  KEY `dd_in_2` (`DECLAREDATE`),
  KEY `IUM51089328` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_ann_security_lst`;

CREATE TABLE `c_ann_security_lst` (
  `ANNOUNCEMENTID` bigint(20) NOT NULL COMMENT '公告ID',
  `SECURITYID` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '相关证券ID',
  `SYMBOL` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券代码',
  `SECURITYTYPEID` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券类别编码',
  `SECURITYTYPE` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券类别',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公告日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`ANNOUNCEMENTID`,`SECURITYID`),
  KEY `dd_in_3` (`DECLAREDATE`),
  KEY `IUM51089337` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_ann_summaryinfo_lst`;

CREATE TABLE `c_ann_summaryinfo_lst` (
  `ANNOUNCEMENTID` bigint(20) NOT NULL COMMENT '公告ID',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公告日期',
  `SUMMARYTITLE` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '摘要标题',
  `SUMMARYCONTENT` longtext COMMENT '摘要内容',
  `SUMMARYSIZE` int(11) DEFAULT NULL COMMENT '摘要大小',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`ANNOUNCEMENTID`),
  KEY `dd_in_4` (`DECLAREDATE`),
  KEY `IUM51089349` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_news_accessory_lst`;

CREATE TABLE `c_news_accessory_lst` (
  `NEWSID` bigint(20) NOT NULL COMMENT '新闻ID',
  `RANK` smallint(6) NOT NULL COMMENT '附件序号',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公布日期',
  `FULLNAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '附件名称',
  `BRIEF` varchar(510) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '附件简介',
  `ACCESSORYTYPE` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '附件格式',
  `ACCESSORYROUTE` varchar(800) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '附件路径',
  `ACCESSORYSIZE` int(11) DEFAULT NULL COMMENT '附件大小',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`NEWSID`,`RANK`),
  KEY `dd_in_5` (`DECLAREDATE`),
  KEY `IUM51089367` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_news_classify_lst`;

CREATE TABLE `c_news_classify_lst` (
  `NEWSID` bigint(20) NOT NULL COMMENT '新闻ID',
  `CLASSIFYID` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '新闻分类编码',
  `CLASSIFYNAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '新闻分类名称',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`NEWSID`,`CLASSIFYID`),
  KEY `dd_in_6` (`DECLAREDATE`),
  KEY `IUM51089363` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_news_industry_lst`;

CREATE TABLE `c_news_industry_lst` (
  `NEWSID` bigint(20) NOT NULL COMMENT '新闻ID',
  `INDUSTRYCODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '行业编码',
  `INDUSTRYNAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '行业名称',
  `INDUSTRYSYSTEMCODE` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '行业分类标准编码',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`NEWSID`,`INDUSTRYCODE`,`INDUSTRYSYSTEMCODE`),
  KEY `dd_in_7` (`DECLAREDATE`),
  KEY `IUM51089375` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_news_newsinfo_lst`;

CREATE TABLE `c_news_newsinfo_lst` (
  `NEWSID` bigint(20) NOT NULL COMMENT '新闻ID',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公布日期',
  `TITLE` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '标题',
  `NEWSSUMMARY` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '摘要',
  `NEWSCONTENT` longtext COMMENT '正文',
  `KEYWORD` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '关键词',
  `NEWSSOURCE` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '来源',
  `AUTOR` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '作者',
  `ISACCESSORY` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '是否附带附件',
  `FILESIZE` int(11) DEFAULT NULL COMMENT '文本大小',
  `NEWSSOURCEID` bigint(20) DEFAULT NULL COMMENT '来源ID',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`NEWSID`),
  KEY `dd_in_8` (`DECLAREDATE`),
  KEY `IUM51089380` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_news_security_lst`;

CREATE TABLE `c_news_security_lst` (
  `NEWSID` bigint(20) NOT NULL COMMENT '新闻ID',
  `SECURITYID` bigint(20) NOT NULL COMMENT '相关证券ID',
  `SYMBOL` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券代码',
  `SECURITYTYPEID` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '证券类别编码',
  `SECURITYTYPE` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券类别',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '公布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`NEWSID`,`SECURITYID`,`SECURITYTYPEID`),
  KEY `IUM51089388` (`UTSID`),
  KEY `dd_in_9` (`DECLAREDATE`),
  KEY `PK_NEWS_SECURITY` (`NEWSID`,`SECURITYID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_rep_category_lst`;

CREATE TABLE `c_rep_category_lst` (
  `REPORTID` bigint(20) DEFAULT NULL COMMENT '研究报告编码',
  `CATEGORYCODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '发布机构ID',
  `CATEGORY` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '发布机构名称',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`,`CATEGORYCODE`),
  KEY `dd_in_10` (`DECLAREDATE`),
  KEY `IUM45735859` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_rep_industry_lst`;

CREATE TABLE `c_rep_industry_lst` (
  `REPORTID` bigint(20) DEFAULT NULL COMMENT '研究报告编码',
  `INDUSTRYCODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '行业编码',
  `INDUSTRYNAME` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '行业名称',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`,`INDUSTRYCODE`),
  KEY `dd_in_11` (`DECLAREDATE`),
  KEY `IUM55433531` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `c_rep_institution_lst`;

CREATE TABLE `c_rep_institution_lst` (
  `REPORTID` bigint(20) NOT NULL COMMENT '研究报告编码',
  `INSTITUTIONID` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '发布机构ID',
  `INSTITUTIONNAME` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '发布机构名称',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`,`INSTITUTIONID`),
  KEY `dd_in_12` (`DECLAREDATE`),
  KEY `IUM55433511` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_rep_person_lst`;

CREATE TABLE `c_rep_person_lst` (
  `REPORTID` bigint(20) DEFAULT NULL COMMENT '研究报告编码',
  `RESEARCHERNAME` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '研究员姓名',
  `RESEARCHERID` bigint(20) DEFAULT NULL COMMENT '研究员ID',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`,`RESEARCHERID`),
  KEY `dd_in_13` (`DECLAREDATE`),
  KEY `IUM55433543` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_rep_reportinfo_lst`;

CREATE TABLE `c_rep_reportinfo_lst` (
  `REPORTID` bigint(20) NOT NULL COMMENT '研究报告编码',
  `TITLE` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '标题',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `REPORTDATE` datetime DEFAULT NULL COMMENT '报告日期',
  `SUMMARY` longtext COMMENT '摘要',
  `KEYWORDS` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '关键词',
  `FILESTORAGEPATH` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '文件存贮路径',
  `FILETYPE` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '文件类型',
  `FILESIZE` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '文件大小',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`),
  KEY `dd_in_14` (`DECLAREDATE`),
  KEY `IUM55433515` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `c_rep_security_lst`;

CREATE TABLE `c_rep_security_lst` (
  `REPORTID` bigint(20) NOT NULL COMMENT '研究报告编码',
  `SECURITYID` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '证券ID',
  `SYMBOL` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '证券代码',
  `DECLAREDATE` datetime DEFAULT NULL COMMENT '发布日期',
  `UTSID` bigint(20) DEFAULT NULL COMMENT 'UTS专用字段',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '进入时间,在insert时插入,在update时不会变',
  PRIMARY KEY (`REPORTID`,`SECURITYID`),
  KEY `dd_in_15` (`DECLAREDATE`),
  KEY `IUM55433547` (`UTSID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;